name: basic_banking
description: A Flutter Project with integration of Firebase, for basic transaction between users.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: ^4.6.0
  google_sign_in: ^6.1.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.1.0
  provider: ^6.1.2
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600

